openapi: "3.0.0"
info:
  title: "My Project API"
  version: "1.0.0"
  description: >
    وثائق API للمشروع تشمل فقط:
    - تسجيل الدخول باستخدام رقم الموبايل
    - استيراد البيانات بالجملة (Bulk Import)
    - جلب الطلبات الجديدة
    - جلب الطلبات بين تاريخين
    - إرسال OTP
    - إرسال Broadcast
servers:
  - url: "http://localhost:5000"
    description: "WatsOrder Server"
tags:
  - name: "Auth"
    description: "Endpoints لتسجيل الدخول باستخدام رقم الموبايل"
  - name: "BulkImport"
    description: "Endpoints لاستيراد البيانات بالجملة"
  - name: "Orders"
    description: "Endpoints لإدارة الطلبات"
  - name: "OTP"
    description: "Endpoints لإرسال OTP"
  - name: "Broadcast"
    description: "Endpoints لإرسال رسائل Broadcast"
paths:
  /api/auth/login:
    post:
      tags: [Auth]
      summary: "تسجيل الدخول"
      description: "تسجيل الدخول عبر رقم الموبايل وإرجاع توكن JWT عند النجاح."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phoneNumber:
                  type: string
                  description: "رقم الموبايل للمستخدم"
                password:
                  type: string
                  description: "كلمة المرور"
      responses:
        "200":
          description: "تم تسجيل الدخول بنجاح"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  message:
                    type: string
        "400":
          description: "حقول مفقودة أو بيانات غير صحيحة"
        "500":
          description: "خطأ في الخادم"
  /api/bulk-import/{sessionId}:
    post:
      tags: [BulkImport]
      summary: "إدخال بيانات بالجملة"
      description: "إدخال بيانات الأصناف والمنتجات لجلسة محددة."
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                categories:
                  type: array
                  items:
                    type: object
                    properties:
                      category_name:
                        type: string
                      category_internal_code:
                        type: string
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      product_name:
                        type: string
                      category_id:
                        type: integer
                      price:
                        type: number
                      product_internal_code:
                        type: string
      responses:
        "201":
          description: "تم الإدخال بنجاح"
        "400":
          description: "رقم الجلسة غير صالح أو بيانات ناقصة"
        "403":
          description: "غير مصرح"
        "500":
          description: "خطأ في الخادم"
  /api/orders/new:
    get:
      tags: [Orders]
      summary: "عرض الطلبات الجديدة"
      description: "جلب الطلبات الجديدة للمستخدم الحالي."
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "قائمة الطلبات الجديدة"
        "401":
          description: "غير مصرح"
        "500":
          description: "خطأ في الخادم"
  /api/orders/date-range:
    get:
      tags: [Orders]
      summary: "عرض الطلبات بين تاريخين"
      description: "جلب الطلبات التي تمت بين تاريخين محددين."
      security:
        - bearerAuth: []
      parameters:
        - name: startDate
          in: query
          description: "تاريخ البدء (YYYY-MM-DD)"
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          description: "تاريخ الانتهاء (YYYY-MM-DD)"
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: "قائمة الطلبات بين التاريخين"
        "400":
          description: "المدخلات غير صالحة"
        "401":
          description: "غير مصرح"
        "500":
          description: "خطأ في الخادم"
  /api/otp/send:
    post:
      tags: [OTP]
      summary: "إرسال OTP"
      description: "إرسال رمز OTP إلى رقم الهاتف المحدد."
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sessionId:
                  type: integer
                phoneNumber:
                  type: string
      responses:
        "200":
          description: "تم إرسال OTP بنجاح"
          content:
            application/json:
              schema:
                type: object
                properties:
                  otpCode:
                    type: string
        "400":
          description: "الحقول مفقودة"
        "404":
          description: "الجلسة أو عميل OTP غير موجود"
        "500":
          description: "خطأ في الخادم"
  /api/sessions/{id}/broadcast:
    post:
      tags: [Broadcast]
      summary: "إرسال Broadcast"
      description: "إرسال رسالة برودكاست إلى مجموعة من أرقام الهاتف مع إمكانية إرسال ميديا."
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phoneNumbers:
                  type: array
                  items:
                    type: string
                message:
                  type: string
                randomNumbers:
                  type: array
                  items:
                    type: integer
                  example: [1, 2]
                media:
                  type: array
                  items:
                    type: object
                    properties:
                      mimetype:
                        type: string
                      base64:
                        type: string
                      filename:
                        type: string
      responses:
        "200":
          description: "تم بدء البث بنجاح"
        "400":
          description: "بيانات غير صالحة أو الحالة غير Connected"
        "404":
          description: "الجلسة أو عميل OTP غير موجود"
        "500":
          description: "خطأ في الخادم"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
